#!/usr/bin/env bash.origin
eval BO_SELF_BASH_SOURCE="$BO_READ_SELF_BASH_SOURCE"
BO_deriveSelfDir ___TMP___ "$BO_SELF_BASH_SOURCE"
local __BO_DIR__="$___TMP___"


pushd "$__BO_DIR__" > /dev/null

		# NOTE: For full test suite see 'bash.origin.modules'

		BO_requireModule "./module.bo.sh" as "module"

		module run "from main"

printenv

echo "SHELL: $SHELL"

echo "---1-"

		bash ./script.bo.sh

echo "---11-"

		./script.bo.sh

echo "---111-"

popd > /dev/null
