#!/bin/bash
# Source https://github.com/cadorn/bash.origin
. "$HOME/bash.origin"
function init {
	eval BO_SELF_BASH_SOURCE="$BO_READ_SELF_BASH_SOURCE"
	BO_deriveSelfDir ___TMP___ "$BO_SELF_BASH_SOURCE"
	local __BO_DIR__="$___TMP___"

	function format {
		if [ "$1" == "HEADER" ]; then
			echo "##################################################";
			echo "# $2";
			echo "##################################################";
		fi
		if [ "$1" == "FOOTER" ]; then
			echo "##################################################";
			echo ""
		fi
	}

	function install {
		format "HEADER" "Installing latest 'bash.origin'"
		pushd "$__BO_DIR__"
			BO_run_npm install
		popd
		format "FOOTER"
	}

	function run {
		format "HEADER" "$1"
		"$__BO_DIR__/examples/$1/main"
		format "FOOTER"
	}

	install

	run "01-HelloWorld"
	run "02-SourceMultiplePrototypes"
	run "03-CliPlugin"
	run "04-ProvisionWithSMI"
	run "05-DownloadToSystemCache"
}
init