#!/bin/bash
# Source https://github.com/cadorn/bash.origin
. "$HOME/.bash.origin"
function init {
  	eval BO_SELF_BASH_SOURCE="$BO_READ_SELF_BASH_SOURCE"
  	BO_deriveSelfDir ___TMP___ "$BO_SELF_BASH_SOURCE"
  	local __BO_DIR__="$___TMP___"


    BO_callPlugin "bash.origin.provision@master" BO_Provision_ensureGitWorkingRepositoryAt ".tmp~io.pinf.proxy" "git@github.com:pinf-io/io.pinf.proxy.git"

    # TODO: Assertions

    echo "OK"
}
init "$@"
