#!/usr/bin/env bash
# Source https://github.com/cadorn/bash.origin
if [ -z "${BO_LOADED}" ]; then
		. "../../bash.origin"
fi
function init {
		eval BO_SELF_BASH_SOURCE="$BO_READ_SELF_BASH_SOURCE"
		BO_deriveSelfDir ___TMP___ "$BO_SELF_BASH_SOURCE"
		local __BO_DIR__="$___TMP___"



		BO_sourcePrototype "$__BO_DIR__/bin/hello" "Hi bash.origin, you super cool coatrack for my bootstrapping logic"
		BO_sourcePrototype "$__BO_DIR__/bin/hallo" "Hi bash.origin, you super cool coatrack for my bootstrapping logic"
		BO_sourcePrototype "$__BO_DIR__/bin/hola" "Hi bash.origin, you super cool coatrack for my bootstrapping logic"
}
init
